---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  - name: Create an empty bucket
    aws_s3:
      bucket: mybucket_acloudguru_113355
      mode: create
      permission: public-read
  - name: Simple PUT operation
    aws_s3:
      bucket: mybucket_acloudguru_113355
      object: /my/desired/key.txt
      src: /tmp/file1
      mode: put
  - ec2:
      key_name: /etc/ansible/mykey
      instance_type: t2.micro
      image: ami-0e34e7b9ca0ace12d
      wait: yes
      group: webserver
      count: 1
      vpc_subnet_id: subnet-03a9fc3fdfdbb5efc
      assign_public_ip: yes
