---
- hosts: all

  vars:
    username: Rose
    lock_file: /tmp/ansible-playbook-{{username}}.lock

  tasks:

  - name: check for lock file
    wait_for:
      path: "{{lock_file}}"
      state: absent
  - name: create lock file
    file:
      path: "{{lock_file}}"
      state: touch

  - name: Check whether there's your user on the machine
    action: shell /usr/bin/getent passwd {{username}} | /usr/bin/wc -l | tr -d ''      
    register: user_exist
  - debug:
      var=user_exist
  
  - name: Creating an user, If the user does not exits
    user: name={{username}} state=present
    when:
      - user_exist['stdout'] == "0"

  - name: remove lock file
    file:
      path: "{{lock_file}}"
      state: absent
