---
- hosts: localhost
  tasks:
  - name: security group and port creation
    ec2_group:
      name: myWebSecurity
      description: an websecurity EC2 group
      vpc_id: vpc-0220265f0706fff5e
      region: us-west-2
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
        - proto: tcp
          ports:
          - 80
          cidr_ip: 10.0.0.0/8
